apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - name: auth-deployment
        image: sheriffexcel/middle-ware-app
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: auth-deployment
spec:
  selector:
    app: auth-deployment
  ports:
  - port: 80
    targetPort: 3000

