apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  mongourl: bW9uZ29kYitzcnY6Ly9pc2FhY2FtYmkyOkJvYm9jeTIwMDZAY2x1c3RlcjAuc3VqbG8zNi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
